import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TerminalContextProvider } from "react-terminal";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased scroll-smooth"
        )}
      >
        {children}
      </body>
    </html>
  );
}
